### ISSUE TITLE
IPFS Desktop Crashed

### ISSUE THREAD

**Issue by agnelvishal** [ipfs-shipyard/ipfs-webui#1670] opened 2020-10-13 14:36 UTC
Just installed IPFS Desktop. Was using it for a while and pinned files. Then IPFS Desktop crashed and got error. Restart solved the issue. 

**Specifications**

- **OS**: Ubuntu 16.04
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (/opt/IPFS Desktop/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by jessicaschilling** [comment] 2020-10-26 16:06
Closing, as is duplicate of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1702.

**Closed by jessicaschilling** 2020-10-26 16:06 UTC
Labels: need/triage
