### ISSUE TITLE
https://webui.ipfs.io can't access API througt my lan IP

### ISSUE THREAD

**Issue by D4ryl00** [ipfs-shipyard/ipfs-webui#1510] opened 2020-06-02 07:36 UTC
**Describe the bug**
I don't know why https://webui.ipfs.io can't access to my API via my IP lan address (eg. 10.0.0.11) although that works when the `API` listen to `127.0.0.1`.
I set `CORS` and `API address`:
```
% cat ~/.ipfs/config | head -n 23
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/10.0.0.11/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
```

Furthermore, that works on http://10.0.0.11:5001/webui

**To Reproduce**
1. Set `CORS` and `API address` on cli:
```
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["POST"]'
```
2. Run `ipfs daemon`
3. Go to https://webui.ipfs.io
4. On the bottom of this web page, set manually the `API address`: `/ip4/10.0.0.11/tcp/5001`
5. The `ipfs webui` can't find the `API`

**Expected behavior**
https://webui.ipfs.io is connected to the API.

**Desktop:**
 - OS: macOS Catalina (10.15.4)
 - Browser: firefox 76.0.1
 - IPFS version 0.5.1

**Comment by jessicaschilling** [comment] 2020-07-01 16:24
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment] 2020-07-01 18:38
@D4ryl00 I suspect this is caused by Firefox blocking loading "mixed active content"... by default now Firefox will block requests to `http` urls from a page that was loaded over `https`, see: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

If you are comfortable with the dev tools in Firefox, you can verify that by repeating the steps and checking for a console error line similar to:

<img width="1056" alt="Screenshot 2020-07-01 at 19 26 55" src="https://user-images.githubusercontent.com/58871/86279292-af30ee80-bbd1-11ea-9e88-e6efd2073b0c.png">

I believe Chromium based browser do not have the same restriction. We are unlikely to get time to come up with a fix for this any time soon, but good ideas for solutions and patches are welcome! I suspect the only immediate solutions will be, figure out how to get Firefox to drop the restriction for that IP if possible, or set up a valid https cert for a domain for your IPFS node, via nginx and letsencrypt or similar, which is non-trivial.

Can you confirm that it is the mixed content issue that you are hitting?

**Comment by D4ryl00** [comment] 2020-07-01 20:27
Yes, I've just checked the console and **both** Firefox and Google Chrome block _mixed active content_ by default as you said.

**Comment by olizilla** [comment] 2020-07-02 07:52
Ok, I'm gonna go close this out as known issue. It's worth noting that webui.ipfs.io always points to the bleeding edge, latest commit, so if you can deal with using the local ip for your IPFS node instead, you'll have a more stable time of it.

**Closed by olizilla** 2020-07-02 07:52 UTC
Labels: need/author-input, status/blocked
