### ISSUE TITLE
Add loading indicator on file preview page

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#991] opened 2019-03-14 09:05 UTC
A file preview can take a a few seconds to show up, but there is no indication in the UI that anything is a happening.

**Comment by jessicaschilling** [comment] 2020-04-08 19:51
NOTE: There's a duplicate of this issue for Companion in https://github.com/ipfs-shipyard/ipfs-companion/issues/727. Let's treat that issue as the master, and ensure whatever happens there can be implemented in WebUI.

**Comment by jessicaschilling** [comment] 2020-07-30 18:34
@rafaelramalho19 - does #1570 close this?

**Comment by rafaelramalho19** [comment] 2020-07-31 15:34
Yes 😄

**Closed by rafaelramalho19** 2020-07-31 15:34 UTC
Labels: P1, dif/medium, effort/days, help wanted, kind/bug, status/ready, topic/design-ux, topic/design-visual
