### ISSUE TITLE
bafyHash of https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4 is not matching the bafyHash when you 'ipfs add' the extracted tarball

### ISSUE THREAD

**Issue by timecast** [ipfs-shipyard/ipfs-webui#1727] opened 2021-03-04 09:13 UTC
**Describe the bug**
The CID bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i that is published with the release https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4 is not the same when you really add it to an ipfs node/cluster

**To Reproduce**
with release tarball:
1. download and extract the tarball from https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4
2. add via 'ipfs-cluster-ctl add --cid-version 1 -r build/' -> 'added bafybeiftltn2yzptjbsgapijtsvqvqp2njsmrwb5roh3p7niuiazgwoyu4 build' (same result with 'ipfs add ...')

with IPFS published CID
1. curl https://ipfs.io/api/v0/get/bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i | tar -xf -
2. add via 'ipfs-cluster-ctl add --cid-version 1 -r bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/' -> 'added bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i' (same result with 'ipfs add ...')

**Expected behavior**
I would expect that the published release CID is matching the ipfs add result

**Additional context**
I tested this only with ipfs-go v0.8.0 and ipfs-webui v.2.11.4

This "problem" makes it almost impossible to install the webui manually on a complete private cluster. The only workaround is to extract the data from the live ipfs network.

These is a short information of the diff:

diff -q bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/ build/
Files bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/asset-manifest.json and build/asset-manifest.json differ
Files bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/index.html and build/index.html differ
Common subdirectories: bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/locales and build/locales
Only in bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/: precache-manifest.4686db5361ab677ea4525b6afb3c832f.js
Only in build/: precache-manifest.6aeac0a5ab5b60fe41c2ec67950b69d8.js
Files bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/service-worker.js and build/service-worker.js differ
Common subdirectories: bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i/static and build/static

**Comment by lidel** [comment] 2021-03-04 13:12
@timecast thank you for reporting this. 

Indeed, the problem is that `.tar.gz` attached to tag is built separately by a different CI job than the one run for tag build (one is CircleCi, one is Github, and with JS you can get different output unless build chain versions are aligned).

## Fix

This should be fixed when we move from TravisCI to Github Actions.
We are already tracking this in #1595 so I'm closing this one as a duplicate.

## Temporary workaround

1. Export DAG for release CID from a node that has access to public swarm:
    ```
    $ ipfs dag export bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i > webui.car
    ```
2.  Import it on your private nodes:
    ```console
    $ ipfs dag import webui.car
    Pinned root	bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i	success
    ```

**Closed by lidel** 2021-03-04 13:12 UTC
Labels: status/duplicate
